all_parameters = { "losses": True,
                "hidden_activations": True,
                "m_output_corrs": True,
                "l_output_corrs": True,
                "m_hidden_corrs": True,
                "l_hidden_corrs": True,
                "output_matrices": True,
                "hidden_matrices": True,
                "output_ratio_tests": True,
                "hidden_ratio_tests": True,
                "output_activation_exemplar_tests": True,
                "output_activation_onehot_tests": True}


correlation_parameters = { "losses": True,
                "hidden_activations": False,
                "m_output_corrs": True,
                "l_output_corrs": True,
                "m_hidden_corrs": True,
                "l_hidden_corrs": True,
                "output_matrices": False,
                "hidden_matrices": False,
                "output_ratio_tests": False,
                "hidden_ratio_tests": False,
                "output_activation_exemplar_tests": False,
                "hidden_activation_exemplar_tests": False,
                "output_activation_onehot_tests": False,
                "hidden_activation_onehot_tests": False }